image: "python:3.7"

before_script:
  - python --version
  - pip install -r requirements.txt
  - apt-get install gdal-bin
  - apt-get install libgdal-dev
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/


stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  allow_failure: true
  script:
  - flake8 --max-line-length=120 Pipeline/*.py
  - flake8 --max-line-length=120 Download/*.py

pytest:
  stage: Test
  script:
  - python -m pytest Pipeline/test.py
